node{

  stage('SCM Checkout'){
    git branch: 'main', url: 'https://github.com/didokabanga/jenkins-apps.git'
  }

  stage('Compile-Package'){
    // Get Maven Home Path
    def mavenHome =  tool name: 'MY_MAVEN3', type: 'maven'
    sh "{mavenHome}/bin/mvn package"
  }

}
