pipeline {

  agent any

  environment {
     PATH = "/opt/maven/bin:$PATH"
  }

  stages {

    stage("Git Checkout"){
      steps{
          git branch: 'main', url: 'https://github.com/didokabanga/jenkins-apps.git'
      }
    }

    stage("Maven Build"){
      steps{
          sh "mvn clean package"
      }
    }

  }

}
