pipeline {

  agent any

  environment {
    PATH = "/opt/maven/bin:${env.PATH}"
    MAVEN_HOME = tool name: 'MY_MAVEN3', type: 'maven'
  }

  stages {

    stage("Git Checkout"){
      steps{
          git branch: 'main', url: 'https://github.com/didokabanga/jenkins-apps.git'
      }
    }

    stage("Maven Build"){
      steps{
          echo "PATH is: ${MAVEN_HOME}"
          sh "${MAVEN_HOME}/bin/mvn package"
      }
    }

  }

}
